# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import embeddings_pb2 as embeddings__pb2


class EmbeddingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessEmbeddings = channel.unary_unary(
                '/Embeddings/ProcessEmbeddings',
                request_serializer=embeddings__pb2.EmbeddingsRequest.SerializeToString,
                response_deserializer=embeddings__pb2.EmbeddingsResponse.FromString,
                )


class EmbeddingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessEmbeddings,
                    request_deserializer=embeddings__pb2.EmbeddingsRequest.FromString,
                    response_serializer=embeddings__pb2.EmbeddingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Embeddings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Embeddings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Embeddings/ProcessEmbeddings',
            embeddings__pb2.EmbeddingsRequest.SerializeToString,
            embeddings__pb2.EmbeddingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
